[2022-10-31 23:18:02,998] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-19T00:00:00+00:00 [queued]>
[2022-10-31 23:18:03,009] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-19T00:00:00+00:00 [queued]>
[2022-10-31 23:18:03,009] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-31 23:18:03,009] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-31 23:18:03,009] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-31 23:18:03,748] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-19 00:00:00+00:00
[2022-10-31 23:18:03,752] {standard_task_runner.py:52} INFO - Started process 57798 to run task
[2022-10-31 23:18:03,768] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-19T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpq8ki5z0n', '--error-file', '/tmp/tmp8rs195mm']
[2022-10-31 23:18:03,769] {standard_task_runner.py:80} INFO - Job 15: Subtask cria_pasta
[2022-10-31 23:18:05,671] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-19T00:00:00+00:00 [running]> on host nayara-S14SL01
[2022-10-31 23:18:06,689] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-09-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-19T00:00:00+00:00
[2022-10-31 23:18:06,694] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-10-31 23:18:06,696] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/millenagena/Documents/airflowalura/semana=2022-09-26"']
[2022-10-31 23:18:06,722] {subprocess.py:85} INFO - Output:
[2022-10-31 23:18:06,729] {subprocess.py:92} INFO - mkdir: não foi possível criar o diretório “/home/millenagena”: Permissão negada
[2022-10-31 23:18:06,729] {subprocess.py:96} INFO - Command exited with return code 1
[2022-10-31 23:18:06,754] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nayara/Documentos/airflowalura/venv/lib/python3.9/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-10-31 23:18:06,760] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220919T000000, start_date=20221101T021802, end_date=20221101T021806
[2022-10-31 23:18:07,430] {standard_task_runner.py:92} ERROR - Failed to execute job 15 for task cria_pasta (Bash command failed. The command returned a non-zero exit code 1.; 57798)
[2022-10-31 23:18:07,473] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-31 23:18:08,017] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-10-31 23:18:08,047] {dagrun.py:547} ERROR - Marking run <DagRun dados_climaticos @ 2022-09-19 00:00:00+00:00: scheduled__2022-09-19T00:00:00+00:00, externally triggered: False> failed
[2022-10-31 23:18:08,048] {dagrun.py:607} INFO - DagRun Finished: dag_id=dados_climaticos, execution_date=2022-09-19 00:00:00+00:00, run_id=scheduled__2022-09-19T00:00:00+00:00, run_start_date=2022-11-01 02:17:57.531489+00:00, run_end_date=2022-11-01 02:18:08.048193+00:00, run_duration=10.516704, state=failed, external_trigger=False, run_type=scheduled, data_interval_start=2022-09-19 00:00:00+00:00, data_interval_end=2022-09-26 00:00:00+00:00, dag_hash=3cf75613c8ad6601a62ad0bc0234a5d2
[2022-10-31 23:23:31,294] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-19T00:00:00+00:00 [queued]>
[2022-10-31 23:23:31,400] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-19T00:00:00+00:00 [queued]>
[2022-10-31 23:23:31,400] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-31 23:23:31,400] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-31 23:23:31,400] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-31 23:23:33,255] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-19 00:00:00+00:00
[2022-10-31 23:23:33,267] {standard_task_runner.py:52} INFO - Started process 58609 to run task
[2022-10-31 23:23:33,281] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-19T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpo3x3u88s', '--error-file', '/tmp/tmpzcbyosj9']
[2022-10-31 23:23:33,283] {standard_task_runner.py:80} INFO - Job 15: Subtask cria_pasta
[2022-10-31 23:23:36,549] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-19T00:00:00+00:00 [running]> on host nayara-S14SL01
[2022-10-31 23:23:39,422] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-09-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-19T00:00:00+00:00
[2022-10-31 23:23:39,425] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-10-31 23:23:39,429] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/millenagena/Documents/airflowalura/semana=2022-09-26"']
[2022-10-31 23:23:39,741] {subprocess.py:85} INFO - Output:
[2022-10-31 23:23:40,026] {subprocess.py:92} INFO - mkdir: não foi possível criar o diretório “/home/millenagena”: Permissão negada
[2022-10-31 23:23:40,027] {subprocess.py:96} INFO - Command exited with return code 1
[2022-10-31 23:23:40,098] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nayara/Documentos/airflowalura/venv/lib/python3.9/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-10-31 23:23:40,106] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220919T000000, start_date=20221101T022331, end_date=20221101T022340
[2022-10-31 23:23:40,959] {standard_task_runner.py:92} ERROR - Failed to execute job 15 for task cria_pasta (Bash command failed. The command returned a non-zero exit code 1.; 58609)
[2022-10-31 23:23:41,015] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-31 23:23:41,997] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-10-31 23:29:32,836] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-19T00:00:00+00:00 [queued]>
[2022-10-31 23:29:32,950] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-19T00:00:00+00:00 [queued]>
[2022-10-31 23:29:32,950] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-31 23:29:32,950] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-31 23:29:32,951] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-31 23:29:33,406] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-19 00:00:00+00:00
[2022-10-31 23:29:33,417] {standard_task_runner.py:52} INFO - Started process 59342 to run task
[2022-10-31 23:29:33,430] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-19T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpsfg1gafl', '--error-file', '/tmp/tmp3welltoa']
[2022-10-31 23:29:33,433] {standard_task_runner.py:80} INFO - Job 15: Subtask cria_pasta
[2022-10-31 23:29:34,001] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-19T00:00:00+00:00 [running]> on host nayara-S14SL01
[2022-10-31 23:29:34,989] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-09-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-19T00:00:00+00:00
[2022-10-31 23:29:34,994] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-10-31 23:29:34,996] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/millenagena/Documents/airflowalura/semana=2022-09-26"']
[2022-10-31 23:29:35,037] {subprocess.py:85} INFO - Output:
[2022-10-31 23:29:35,054] {subprocess.py:92} INFO - mkdir: não foi possível criar o diretório “/home/millenagena”: Permissão negada
[2022-10-31 23:29:35,055] {subprocess.py:96} INFO - Command exited with return code 1
[2022-10-31 23:29:35,084] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nayara/Documentos/airflowalura/venv/lib/python3.9/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-10-31 23:29:35,089] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220919T000000, start_date=20221101T022932, end_date=20221101T022935
[2022-10-31 23:29:35,595] {standard_task_runner.py:92} ERROR - Failed to execute job 15 for task cria_pasta (Bash command failed. The command returned a non-zero exit code 1.; 59342)
[2022-10-31 23:29:35,617] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-31 23:29:36,832] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
