[2022-10-31 23:17:36,199] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-05T00:00:00+00:00 [queued]>
[2022-10-31 23:17:36,212] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-05T00:00:00+00:00 [queued]>
[2022-10-31 23:17:36,212] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-31 23:17:36,212] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-31 23:17:36,212] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-31 23:17:36,712] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-05 00:00:00+00:00
[2022-10-31 23:17:36,717] {standard_task_runner.py:52} INFO - Started process 57690 to run task
[2022-10-31 23:17:36,723] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-05T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpngazs4u5', '--error-file', '/tmp/tmpfmfgndem']
[2022-10-31 23:17:36,724] {standard_task_runner.py:80} INFO - Job 13: Subtask cria_pasta
[2022-10-31 23:17:37,184] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-05T00:00:00+00:00 [running]> on host nayara-S14SL01
[2022-10-31 23:17:38,265] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-09-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-05T00:00:00+00:00
[2022-10-31 23:17:38,266] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-10-31 23:17:38,267] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/millenagena/Documents/airflowalura/semana=2022-09-12"']
[2022-10-31 23:17:38,277] {subprocess.py:85} INFO - Output:
[2022-10-31 23:17:38,280] {subprocess.py:92} INFO - mkdir: não foi possível criar o diretório “/home/millenagena”: Permissão negada
[2022-10-31 23:17:38,280] {subprocess.py:96} INFO - Command exited with return code 1
[2022-10-31 23:17:38,294] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nayara/Documentos/airflowalura/venv/lib/python3.9/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-10-31 23:17:38,298] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220905T000000, start_date=20221101T021736, end_date=20221101T021738
[2022-10-31 23:17:38,805] {standard_task_runner.py:92} ERROR - Failed to execute job 13 for task cria_pasta (Bash command failed. The command returned a non-zero exit code 1.; 57690)
[2022-10-31 23:17:38,823] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-31 23:17:39,986] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-10-31 23:23:03,788] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-05T00:00:00+00:00 [queued]>
[2022-10-31 23:23:03,908] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-05T00:00:00+00:00 [queued]>
[2022-10-31 23:23:03,909] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-31 23:23:03,910] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-31 23:23:03,910] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-31 23:23:04,412] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-05 00:00:00+00:00
[2022-10-31 23:23:04,424] {standard_task_runner.py:52} INFO - Started process 58526 to run task
[2022-10-31 23:23:04,452] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-05T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpmgd9jfe7', '--error-file', '/tmp/tmp0dp1jx9q']
[2022-10-31 23:23:04,455] {standard_task_runner.py:80} INFO - Job 13: Subtask cria_pasta
[2022-10-31 23:23:05,037] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-05T00:00:00+00:00 [running]> on host nayara-S14SL01
[2022-10-31 23:23:05,921] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-09-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-05T00:00:00+00:00
[2022-10-31 23:23:05,926] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-10-31 23:23:05,928] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/millenagena/Documents/airflowalura/semana=2022-09-12"']
[2022-10-31 23:23:05,955] {subprocess.py:85} INFO - Output:
[2022-10-31 23:23:05,961] {subprocess.py:92} INFO - mkdir: não foi possível criar o diretório “/home/millenagena”: Permissão negada
[2022-10-31 23:23:05,961] {subprocess.py:96} INFO - Command exited with return code 1
[2022-10-31 23:23:05,992] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nayara/Documentos/airflowalura/venv/lib/python3.9/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-10-31 23:23:05,997] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220905T000000, start_date=20221101T022303, end_date=20221101T022305
[2022-10-31 23:23:06,552] {standard_task_runner.py:92} ERROR - Failed to execute job 13 for task cria_pasta (Bash command failed. The command returned a non-zero exit code 1.; 58526)
[2022-10-31 23:23:06,584] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-31 23:23:07,513] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-10-31 23:29:08,937] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-05T00:00:00+00:00 [queued]>
[2022-10-31 23:29:09,073] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-05T00:00:00+00:00 [queued]>
[2022-10-31 23:29:09,074] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-31 23:29:09,074] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-31 23:29:09,074] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-31 23:29:09,564] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-05 00:00:00+00:00
[2022-10-31 23:29:09,576] {standard_task_runner.py:52} INFO - Started process 59286 to run task
[2022-10-31 23:29:09,589] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-05T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp_fld4udv', '--error-file', '/tmp/tmp8gkmc97o']
[2022-10-31 23:29:09,590] {standard_task_runner.py:80} INFO - Job 13: Subtask cria_pasta
[2022-10-31 23:29:10,463] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-05T00:00:00+00:00 [running]> on host nayara-S14SL01
[2022-10-31 23:29:11,435] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-09-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-05T00:00:00+00:00
[2022-10-31 23:29:11,437] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-10-31 23:29:11,438] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/millenagena/Documents/airflowalura/semana=2022-09-12"']
[2022-10-31 23:29:11,449] {subprocess.py:85} INFO - Output:
[2022-10-31 23:29:11,452] {subprocess.py:92} INFO - mkdir: não foi possível criar o diretório “/home/millenagena”: Permissão negada
[2022-10-31 23:29:11,452] {subprocess.py:96} INFO - Command exited with return code 1
[2022-10-31 23:29:11,471] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nayara/Documentos/airflowalura/venv/lib/python3.9/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-10-31 23:29:11,474] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220905T000000, start_date=20221101T022909, end_date=20221101T022911
[2022-10-31 23:29:11,888] {standard_task_runner.py:92} ERROR - Failed to execute job 13 for task cria_pasta (Bash command failed. The command returned a non-zero exit code 1.; 59286)
[2022-10-31 23:29:11,929] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-31 23:29:12,661] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
