[2022-10-31 23:17:01,613] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-08-22T00:00:00+00:00 [queued]>
[2022-10-31 23:17:01,631] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-08-22T00:00:00+00:00 [queued]>
[2022-10-31 23:17:01,631] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-31 23:17:01,631] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-31 23:17:01,631] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-31 23:17:02,109] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-08-22 00:00:00+00:00
[2022-10-31 23:17:02,120] {standard_task_runner.py:52} INFO - Started process 57619 to run task
[2022-10-31 23:17:02,145] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-08-22T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpuse3umm4', '--error-file', '/tmp/tmpj62za0gi']
[2022-10-31 23:17:02,149] {standard_task_runner.py:80} INFO - Job 11: Subtask cria_pasta
[2022-10-31 23:17:02,817] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-08-22T00:00:00+00:00 [running]> on host nayara-S14SL01
[2022-10-31 23:17:07,408] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-08-22T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-22T00:00:00+00:00
[2022-10-31 23:17:07,411] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-10-31 23:17:07,414] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/millenagena/Documents/airflowalura/semana=2022-08-29"']
[2022-10-31 23:17:07,434] {subprocess.py:85} INFO - Output:
[2022-10-31 23:17:07,685] {subprocess.py:92} INFO - mkdir: não foi possível criar o diretório “/home/millenagena”: Permissão negada
[2022-10-31 23:17:07,686] {subprocess.py:96} INFO - Command exited with return code 1
[2022-10-31 23:17:07,727] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nayara/Documentos/airflowalura/venv/lib/python3.9/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-10-31 23:17:07,733] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220822T000000, start_date=20221101T021701, end_date=20221101T021707
[2022-10-31 23:17:08,368] {standard_task_runner.py:92} ERROR - Failed to execute job 11 for task cria_pasta (Bash command failed. The command returned a non-zero exit code 1.; 57619)
[2022-10-31 23:17:08,420] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-31 23:17:09,081] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-10-31 23:22:34,145] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-08-22T00:00:00+00:00 [queued]>
[2022-10-31 23:22:34,167] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-08-22T00:00:00+00:00 [queued]>
[2022-10-31 23:22:34,167] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-31 23:22:34,168] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-31 23:22:34,168] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-31 23:22:35,098] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-08-22 00:00:00+00:00
[2022-10-31 23:22:35,108] {standard_task_runner.py:52} INFO - Started process 58458 to run task
[2022-10-31 23:22:35,125] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-08-22T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpwpl91n3d', '--error-file', '/tmp/tmp074g6z8f']
[2022-10-31 23:22:35,129] {standard_task_runner.py:80} INFO - Job 11: Subtask cria_pasta
[2022-10-31 23:22:36,757] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-08-22T00:00:00+00:00 [running]> on host nayara-S14SL01
[2022-10-31 23:22:37,792] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-08-22T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-22T00:00:00+00:00
[2022-10-31 23:22:37,797] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-10-31 23:22:37,800] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/millenagena/Documents/airflowalura/semana=2022-08-29"']
[2022-10-31 23:22:37,828] {subprocess.py:85} INFO - Output:
[2022-10-31 23:22:38,056] {subprocess.py:92} INFO - mkdir: não foi possível criar o diretório “/home/millenagena”: Permissão negada
[2022-10-31 23:22:38,060] {subprocess.py:96} INFO - Command exited with return code 1
[2022-10-31 23:22:38,150] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nayara/Documentos/airflowalura/venv/lib/python3.9/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-10-31 23:22:38,160] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220822T000000, start_date=20221101T022234, end_date=20221101T022238
[2022-10-31 23:22:38,643] {standard_task_runner.py:92} ERROR - Failed to execute job 11 for task cria_pasta (Bash command failed. The command returned a non-zero exit code 1.; 58458)
[2022-10-31 23:22:38,674] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-31 23:22:39,130] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-10-31 23:28:45,495] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-08-22T00:00:00+00:00 [queued]>
[2022-10-31 23:28:45,547] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-08-22T00:00:00+00:00 [queued]>
[2022-10-31 23:28:45,547] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-31 23:28:45,548] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-31 23:28:45,548] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-31 23:28:45,974] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-08-22 00:00:00+00:00
[2022-10-31 23:28:45,982] {standard_task_runner.py:52} INFO - Started process 59233 to run task
[2022-10-31 23:28:45,987] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-08-22T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpaf7j8_7g', '--error-file', '/tmp/tmpn_742kg2']
[2022-10-31 23:28:45,988] {standard_task_runner.py:80} INFO - Job 11: Subtask cria_pasta
[2022-10-31 23:28:46,532] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-08-22T00:00:00+00:00 [running]> on host nayara-S14SL01
[2022-10-31 23:28:47,510] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-08-22T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-22T00:00:00+00:00
[2022-10-31 23:28:47,516] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-10-31 23:28:47,519] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/millenagena/Documents/airflowalura/semana=2022-08-29"']
[2022-10-31 23:28:47,560] {subprocess.py:85} INFO - Output:
[2022-10-31 23:28:47,566] {subprocess.py:92} INFO - mkdir: não foi possível criar o diretório “/home/millenagena”: Permissão negada
[2022-10-31 23:28:47,567] {subprocess.py:96} INFO - Command exited with return code 1
[2022-10-31 23:28:47,585] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nayara/Documentos/airflowalura/venv/lib/python3.9/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-10-31 23:28:47,588] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220822T000000, start_date=20221101T022845, end_date=20221101T022847
[2022-10-31 23:28:48,003] {standard_task_runner.py:92} ERROR - Failed to execute job 11 for task cria_pasta (Bash command failed. The command returned a non-zero exit code 1.; 59233)
[2022-10-31 23:28:48,048] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-31 23:28:49,374] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
