[2022-10-31 23:17:47,136] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-12T00:00:00+00:00 [queued]>
[2022-10-31 23:17:47,143] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-12T00:00:00+00:00 [queued]>
[2022-10-31 23:17:47,143] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-31 23:17:47,144] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-31 23:17:47,144] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-31 23:17:47,599] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-12 00:00:00+00:00
[2022-10-31 23:17:47,606] {standard_task_runner.py:52} INFO - Started process 57718 to run task
[2022-10-31 23:17:47,615] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-12T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp9w1ntuln', '--error-file', '/tmp/tmppak4hzb9']
[2022-10-31 23:17:47,616] {standard_task_runner.py:80} INFO - Job 14: Subtask cria_pasta
[2022-10-31 23:17:48,355] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-12T00:00:00+00:00 [running]> on host nayara-S14SL01
[2022-10-31 23:17:49,910] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-09-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-12T00:00:00+00:00
[2022-10-31 23:17:49,916] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-10-31 23:17:49,918] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/millenagena/Documents/airflowalura/semana=2022-09-19"']
[2022-10-31 23:17:49,951] {subprocess.py:85} INFO - Output:
[2022-10-31 23:17:49,963] {subprocess.py:92} INFO - mkdir: não foi possível criar o diretório “/home/millenagena”: Permissão negada
[2022-10-31 23:17:49,963] {subprocess.py:96} INFO - Command exited with return code 1
[2022-10-31 23:17:50,001] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nayara/Documentos/airflowalura/venv/lib/python3.9/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-10-31 23:17:50,006] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220912T000000, start_date=20221101T021747, end_date=20221101T021750
[2022-10-31 23:17:50,448] {standard_task_runner.py:92} ERROR - Failed to execute job 14 for task cria_pasta (Bash command failed. The command returned a non-zero exit code 1.; 57718)
[2022-10-31 23:17:50,477] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-31 23:17:50,928] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-10-31 23:23:16,770] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-12T00:00:00+00:00 [queued]>
[2022-10-31 23:23:16,878] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-12T00:00:00+00:00 [queued]>
[2022-10-31 23:23:16,879] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-31 23:23:16,879] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-31 23:23:16,879] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-31 23:23:17,408] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-12 00:00:00+00:00
[2022-10-31 23:23:17,420] {standard_task_runner.py:52} INFO - Started process 58555 to run task
[2022-10-31 23:23:17,436] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-12T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp609c88b9', '--error-file', '/tmp/tmpx8xkujbe']
[2022-10-31 23:23:17,440] {standard_task_runner.py:80} INFO - Job 14: Subtask cria_pasta
[2022-10-31 23:23:18,073] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-12T00:00:00+00:00 [running]> on host nayara-S14SL01
[2022-10-31 23:23:19,085] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-09-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-12T00:00:00+00:00
[2022-10-31 23:23:19,087] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-10-31 23:23:19,087] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/millenagena/Documents/airflowalura/semana=2022-09-19"']
[2022-10-31 23:23:19,125] {subprocess.py:85} INFO - Output:
[2022-10-31 23:23:19,130] {subprocess.py:92} INFO - mkdir: não foi possível criar o diretório “/home/millenagena”: Permissão negada
[2022-10-31 23:23:19,131] {subprocess.py:96} INFO - Command exited with return code 1
[2022-10-31 23:23:19,158] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nayara/Documentos/airflowalura/venv/lib/python3.9/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-10-31 23:23:19,164] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220912T000000, start_date=20221101T022316, end_date=20221101T022319
[2022-10-31 23:23:19,483] {standard_task_runner.py:92} ERROR - Failed to execute job 14 for task cria_pasta (Bash command failed. The command returned a non-zero exit code 1.; 58555)
[2022-10-31 23:23:19,536] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-31 23:23:20,064] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-10-31 23:29:20,188] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-12T00:00:00+00:00 [queued]>
[2022-10-31 23:29:20,657] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-12T00:00:00+00:00 [queued]>
[2022-10-31 23:29:20,657] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-31 23:29:20,657] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-31 23:29:20,657] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-31 23:29:21,065] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-12 00:00:00+00:00
[2022-10-31 23:29:21,085] {standard_task_runner.py:52} INFO - Started process 59312 to run task
[2022-10-31 23:29:21,137] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-12T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpagpwdz4i', '--error-file', '/tmp/tmpz7hswii5']
[2022-10-31 23:29:21,139] {standard_task_runner.py:80} INFO - Job 14: Subtask cria_pasta
[2022-10-31 23:29:21,632] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-12T00:00:00+00:00 [running]> on host nayara-S14SL01
[2022-10-31 23:29:22,617] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-09-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-12T00:00:00+00:00
[2022-10-31 23:29:22,624] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-10-31 23:29:22,627] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/millenagena/Documents/airflowalura/semana=2022-09-19"']
[2022-10-31 23:29:22,663] {subprocess.py:85} INFO - Output:
[2022-10-31 23:29:22,670] {subprocess.py:92} INFO - mkdir: não foi possível criar o diretório “/home/millenagena”: Permissão negada
[2022-10-31 23:29:22,670] {subprocess.py:96} INFO - Command exited with return code 1
[2022-10-31 23:29:22,694] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nayara/Documentos/airflowalura/venv/lib/python3.9/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-10-31 23:29:22,698] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220912T000000, start_date=20221101T022920, end_date=20221101T022922
[2022-10-31 23:29:23,074] {standard_task_runner.py:92} ERROR - Failed to execute job 14 for task cria_pasta (Bash command failed. The command returned a non-zero exit code 1.; 59312)
[2022-10-31 23:29:23,119] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-31 23:29:23,475] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
