[2022-10-31 23:24:25,149] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-03T00:00:00+00:00 [queued]>
[2022-10-31 23:24:25,166] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-03T00:00:00+00:00 [queued]>
[2022-10-31 23:24:25,166] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-31 23:24:25,166] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-31 23:24:25,167] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-31 23:24:25,928] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-10-03 00:00:00+00:00
[2022-10-31 23:24:25,934] {standard_task_runner.py:52} INFO - Started process 58685 to run task
[2022-10-31 23:24:25,949] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-10-03T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpwg7azwbg', '--error-file', '/tmp/tmpk2tdrimk']
[2022-10-31 23:24:25,951] {standard_task_runner.py:80} INFO - Job 17: Subtask cria_pasta
[2022-10-31 23:24:27,501] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-03T00:00:00+00:00 [running]> on host nayara-S14SL01
[2022-10-31 23:24:29,207] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-10-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-03T00:00:00+00:00
[2022-10-31 23:24:29,209] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-10-31 23:24:29,209] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/millenagena/Documents/airflowalura/semana=2022-10-10"']
[2022-10-31 23:24:29,221] {subprocess.py:85} INFO - Output:
[2022-10-31 23:24:29,225] {subprocess.py:92} INFO - mkdir: não foi possível criar o diretório “/home/millenagena”: Permissão negada
[2022-10-31 23:24:29,225] {subprocess.py:96} INFO - Command exited with return code 1
[2022-10-31 23:24:29,245] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nayara/Documentos/airflowalura/venv/lib/python3.9/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-10-31 23:24:29,248] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221003T000000, start_date=20221101T022425, end_date=20221101T022429
[2022-10-31 23:24:29,713] {standard_task_runner.py:92} ERROR - Failed to execute job 17 for task cria_pasta (Bash command failed. The command returned a non-zero exit code 1.; 58685)
[2022-10-31 23:24:29,740] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-31 23:24:30,243] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
