[2022-10-31 23:24:01,216] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-26T00:00:00+00:00 [queued]>
[2022-10-31 23:24:01,234] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-26T00:00:00+00:00 [queued]>
[2022-10-31 23:24:01,234] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-31 23:24:01,234] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-31 23:24:01,234] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-31 23:24:01,803] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-26 00:00:00+00:00
[2022-10-31 23:24:01,808] {standard_task_runner.py:52} INFO - Started process 58635 to run task
[2022-10-31 23:24:01,820] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-26T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmprbbdp6oo', '--error-file', '/tmp/tmp9pwprv5y']
[2022-10-31 23:24:01,822] {standard_task_runner.py:80} INFO - Job 16: Subtask cria_pasta
[2022-10-31 23:24:03,092] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-26T00:00:00+00:00 [running]> on host nayara-S14SL01
[2022-10-31 23:24:04,500] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-09-26T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-26T00:00:00+00:00
[2022-10-31 23:24:04,502] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-10-31 23:24:04,503] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/millenagena/Documents/airflowalura/semana=2022-10-03"']
[2022-10-31 23:24:04,540] {subprocess.py:85} INFO - Output:
[2022-10-31 23:24:04,543] {subprocess.py:92} INFO - mkdir: não foi possível criar o diretório “/home/millenagena”: Permissão negada
[2022-10-31 23:24:04,544] {subprocess.py:96} INFO - Command exited with return code 1
[2022-10-31 23:24:04,569] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nayara/Documentos/airflowalura/venv/lib/python3.9/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-10-31 23:24:04,576] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220926T000000, start_date=20221101T022401, end_date=20221101T022404
[2022-10-31 23:24:05,086] {standard_task_runner.py:92} ERROR - Failed to execute job 16 for task cria_pasta (Bash command failed. The command returned a non-zero exit code 1.; 58635)
[2022-10-31 23:24:05,127] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-31 23:24:05,874] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
