[2022-10-31 23:24:46,631] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-10T00:00:00+00:00 [queued]>
[2022-10-31 23:24:46,640] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-10T00:00:00+00:00 [queued]>
[2022-10-31 23:24:46,640] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-31 23:24:46,640] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-31 23:24:46,640] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-31 23:24:47,194] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-10-10 00:00:00+00:00
[2022-10-31 23:24:47,203] {standard_task_runner.py:52} INFO - Started process 58725 to run task
[2022-10-31 23:24:47,216] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-10-10T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp69m6eg50', '--error-file', '/tmp/tmpoa_otxl7']
[2022-10-31 23:24:47,220] {standard_task_runner.py:80} INFO - Job 18: Subtask cria_pasta
[2022-10-31 23:24:48,150] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-10T00:00:00+00:00 [running]> on host nayara-S14SL01
[2022-10-31 23:24:49,850] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-10-10T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-10T00:00:00+00:00
[2022-10-31 23:24:49,854] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-10-31 23:24:49,856] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/millenagena/Documents/airflowalura/semana=2022-10-17"']
[2022-10-31 23:24:49,883] {subprocess.py:85} INFO - Output:
[2022-10-31 23:24:49,894] {subprocess.py:92} INFO - mkdir: não foi possível criar o diretório “/home/millenagena”: Permissão negada
[2022-10-31 23:24:49,895] {subprocess.py:96} INFO - Command exited with return code 1
[2022-10-31 23:24:49,930] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nayara/Documentos/airflowalura/venv/lib/python3.9/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-10-31 23:24:49,937] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221010T000000, start_date=20221101T022446, end_date=20221101T022449
[2022-10-31 23:24:50,780] {standard_task_runner.py:92} ERROR - Failed to execute job 18 for task cria_pasta (Bash command failed. The command returned a non-zero exit code 1.; 58725)
[2022-10-31 23:24:50,803] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-31 23:24:51,421] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-10-31 23:24:51,448] {dagrun.py:547} ERROR - Marking run <DagRun dados_climaticos @ 2022-10-10 00:00:00+00:00: scheduled__2022-10-10T00:00:00+00:00, externally triggered: False> failed
[2022-10-31 23:24:51,449] {dagrun.py:607} INFO - DagRun Finished: dag_id=dados_climaticos, execution_date=2022-10-10 00:00:00+00:00, run_id=scheduled__2022-10-10T00:00:00+00:00, run_start_date=2022-11-01 02:24:36.016529+00:00, run_end_date=2022-11-01 02:24:51.449456+00:00, run_duration=15.432927, state=failed, external_trigger=False, run_type=scheduled, data_interval_start=2022-10-10 00:00:00+00:00, data_interval_end=2022-10-17 00:00:00+00:00, dag_hash=3cf75613c8ad6601a62ad0bc0234a5d2
